### ISSUE TITLE
Vee-validate 3

### ISSUE THREAD

**Issue by bpuig** [Sammyjo20/laravel-veevalidate#2]
Hello, thanks for your great work.
Is this supported for vee-validate 3?

**Comment by Sammyjo20** [comment]
Thank you! ❤️Not yet, I'm currently researching VeeValidate v3 and will hopefully release a new version of Laravel VeeValidate for V3. Do you have any suggestions for the new version?

**Comment by bpuig** [comment]
> I'm currently researching VeeValidate v3

I'm still there too, just got it working and implementing it to my vue. It changed a lot of how things worked, mostly every validation has to be rewritten.

Thanks for your reply :)

**Comment by acirinelli** [comment]
Has there been any update on this?

**Comment by Sammyjo20** [comment]
@acirinelli Not just yet, been super busy. I'll take a look over the next couple of days, hang tight. 🚀

**Comment by Sammyjo20** [comment]
Hey @acirinelli thanks for waiting the last few days. I've taken a look but it's something I'm not prepared to update at this point in time. I'd love to release this as a new version of VeeValidate at some point in the future but I'm currently quite busy with work life as it is. Thanks for your interest, it really mean a lot! ❤️
